
#map design
tilemap =   [
			[FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,WALL, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR],
			[FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, DOOR],
			[FLOOR, WALL, FLOOR,FLOOR, WALL, WALL,FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR,FLOOR, WALL, GUARDIAN],
			[FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,WALL, WALL, FLOOR,FLOOR, WALL, FLOOR],
			[FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,WALL, WALL, FLOOR,WALL, WALL, FLOOR],
			[FLOOR, FLOOR, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, WALL,FLOOR, WALL, FLOOR],
			[FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR],
			[FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR],
			[FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR],
			[FLOOR, WALL, FLOOR,FLOOR, WALL, WALL,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR],
			[START, WALL, WALL,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR],
			[FLOOR, WALL, FLOOR,WALL, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR],
			[FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,WALL, WALL, FLOOR,WALL, WALL, WALL,FLOOR, WALL, FLOOR],
			[FLOOR, WALL, FLOOR,FLOOR, WALL, FLOOR,WALL, WALL, FLOOR,WALL, FLOOR, FLOOR,FLOOR, WALL, FLOOR],
			[FLOOR, FLOOR, FLOOR,FLOOR, FLOOR, FLOOR,FLOOR, WALL, FLOOR,FLOOR, FLOOR, FLOOR,FLOOR, WALL, FLOOR],
			]

#images dict
Pics = {
			WALL : pygame.image.load("wall1.png").convert(),
			FLOOR : pygame.image.load("floor1.jpg").convert(),
			DOOR : pygame.image.load("door.jpg").convert(),
			MAC : pygame.image.load("mac_gyver.png").convert(),
			GUARDIAN : pygame.image.load("GUARDIAN.png").convert(),
			ITEM1 : pygame.image.load("key1.jpg").convert_alpha(),
			ITEM2 : pygame.image.load("key2.jpg").convert_alpha(),
			ITEM3 : pygame.image.load("key3.jpg").convert_alpha()
		}

#window parameters

WINDOW_HEIGHT = 645
WINDOW_WIDHT = 480
1SPRITE_HEIGHT = WINDOW_HEIGHT/15
1SPRITE_WIDHT = WINDOW_WIDHT/15